export const customLocale = {
    lang: {
        locale: 'vi',
        placeholder: 'Chọn ngày',
        rangePlaceholder: ['Ngày bắt đầu', 'Ngày kết thúc'],
        today: 'Hôm nay',
        now: 'Bây giờ',
        backToToday: 'Quay lại',
        ok: 'Đồng ý',
        clear: 'Xóa',
        month: 'Tháng',
        year: 'Năm',
        timeSelect: 'Chọn thời gian',
        dateSelect: 'Chọn ngày',
        weekSelect: 'Chọn tuần',
        monthSelect: 'Chọn tháng',
        yearSelect: 'Chọn năm',
        decadeSelect: 'Chọn thập kỷ',
        yearFormat: 'YYYY',
        dateFormat: 'DD/MM/YYYY',
        dayFormat: 'D',
        dateTimeFormat: 'DD/MM/YYYY HH:mm:ss',
        monthBeforeYear: true,
        previousMonth: 'Tháng trước',
        nextMonth: 'Tháng sau',
        previousYear: 'Năm trước',
        nextYear: 'Năm sau',
        previousDecade: 'Thập kỷ trước',
        nextDecade: 'Thập kỷ sau',
        previousCentury: 'Thế kỷ trước',
        nextCentury: 'Thế kỷ sau',
        shortWeekDays: ['T2', 'T3', 'T4', 'T5', 'T6', 'T7', 'CN'],
        shortMonths: ['Thg 1', 'Thg 2', 'Thg 3', 'Thg 4', 'Thg 5', 'Thg 6', 'Thg 7', 'Thg 8', 'Thg 9', 'Thg 10', 'Thg 11', 'Thg 12'],
    },
};

